require "prawn"
require "prawn/table"

class ParticipantReportPdf < Prawn::Document
  def initialize(participants, institute)
    super(page_layout: :landscape)
    @participants = participants
    @institute = institute
    generate_content
  end

  def generate_content
    header
    participant_details
    footer
  end

  private

  def header
    text "#{@institute.name} - Participant Report", size: 18, style: :bold, align: :center
    text "Generated on: #{Time.current.strftime('%B %d, %Y at %I:%M %p')}", size: 10, align: :center
    move_down 20
  end

  def participant_details
    table participant_data do
      row(0).font_style = :bold
      row(0).background_color = "DDDDDD"
      self.header = true
      self.row_colors = [ "FFFFFF", "F0F0F0" ]
      self.cell_style = { size: 9, padding: [ 5, 5, 5, 5 ] }
    end
  end

  def participant_data
    [ [ "ID", "Name", "Email", "Section", "Training Programs", "Completed", "Active", "Enrollment Date", "Status" ] ] +
    @participants.map do |participant|
      [
        participant.id,
        participant.user.full_name,
        participant.user.email,
        participant.section&.name || "Not Assigned",
        participant.all_training_programs.count,
        participant.completed_programs.count,
        participant.ongoing_programs.count,
        participant.enrollment_date&.strftime("%B %d, %Y"),
        participant.status.titleize
      ]
    end
  end

  def footer
    move_down 20
    text "Total Participants: #{@participants.count}", size: 10, style: :bold
    text "Active Participants: #{@participants.active.count}", size: 10
    text "Report generated by #{@institute.name}", size: 8, align: :right, style: :italic
  end
end
