require "prawn"
require "prawn/table"

class SectionReportPdf < Prawn::Document
  def initialize(sections, institute)
    super(page_layout: :landscape)
    @sections = sections
    @institute = institute
    generate_content
  end

  def generate_content
    header
    section_details
    footer
  end

  private

  def header
    text "#{@institute.name} - Section Report", size: 18, style: :bold, align: :center
    text "Generated on: #{Time.current.strftime('%B %d, %Y at %I:%M %p')}", size: 10, align: :center
    move_down 20
  end

  def section_details
    table section_data do
      row(0).font_style = :bold
      row(0).background_color = "DDDDDD"
      self.header = true
      self.row_colors = [ "FFFFFF", "F0F0F0" ]
      self.cell_style = { size: 9, padding: [ 5, 5, 5, 5 ] }
    end
  end

  def section_data
    [ [ "ID", "Name", "Code", "Total Participants", "Active Participants",
        "Training Programs", "Active Programs", "Created Date", "Status" ] ] +
    @sections.map do |section|
      [
        section.id,
        section.name,
        section.code,
        section.participants.count,
        section.participants.active.count,
        section.training_programs.count,
        section.training_programs.active.count,
        section.created_at.strftime("%B %d, %Y"),
        section.status.titleize
      ]
    end
  end

  def footer
    move_down 20
    text "Total Sections: #{@sections.count}", size: 10, style: :bold
    text "Active Sections: #{@sections.active.count}", size: 10
    text "Total Participants: #{@sections.sum { |s| s.participants.count }}", size: 10
    text "Report generated by #{@institute.name}", size: 8, align: :right, style: :italic
  end
end
